<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `guru`
//

// `guru`.`table_guru`
$table_guru = array(
  array('id' => '1','nama' => 'Sugiarto S.T.','nip' => '19720317','jenis_kelamin' => 'Laki-laki','agama' => 'Islam','tempat_lahir' => 'Kudus','tanggal_lahir' => '0000-00-00','alamat' => 'Kadisoka, RT 04 / RW 02, Purwomartani, Kalasan, Sleman','status' => 'GPNS','golongan' => 'III/C','mapel_tugas_pokok' => 'Teknik Komputer dan Jaringan','keterangan' => '-','tugas_tambahan' => 'Kepala Jurusan (12 jam/minggu)'),
  array('id' => '2','nama' => 'Rr. Retna Trimantaraningsih S.T.','nip' => '0','jenis_kelamin' => 'Perempuan','agama' => 'Islam','tempat_lahir' => 'Sleman','tanggal_lahir' => '0000-00-00','alamat' => 'KRONGGAHAN I, RT/RW 07/04 ,TRIHANGGO, GAMPING, SLEMAN, YOGYAKARTA, 55291','status' => 'GTT','golongan' => '-','mapel_tugas_pokok' => 'Teknik Komputer dan Jaringan','keterangan' => '','tugas_tambahan' => ''),
  array('id' => '3','nama' => 'Bambang Dwi Sanyata S.T., M.T.','nip' => '19741216','jenis_kelamin' => 'Laki-laki','agama' => 'Islam','tempat_lahir' => 'Bantul','tanggal_lahir' => '0000-00-00','alamat' => 'SORONANGGAN, PANJANGREJO, PUNDONG, BANTUL, YOGYAKARTA 55771','status' => 'GPNS','golongan' => 'III/B','mapel_tugas_pokok' => 'Teknik Komputer dan Jaringan','keterangan' => '','tugas_tambahan' => ''),
  array('id' => '4','nama' => 'Fadilah Damayati S.T.','nip' => '19760930','jenis_kelamin' => 'Perempuan','agama' => 'Islam','tempat_lahir' => 'Yogyakarta','tanggal_lahir' => '0000-00-00','alamat' => 'PERUM TNI AU GRIYA WIRA BUANA, BLOK MERPATI I NO. 4, RT 07 RW 39, TEGALSARI, TIRTOMARTANI, KALASAN, SLEMAN','status' => 'GPNS','golongan' => 'III/B','mapel_tugas_pokok' => 'Teknik Komputer dan Jaringan','keterangan' => '','tugas_tambahan' => ''),
  array('id' => '5','nama' => 'Margaretha Endah Titisari S.T.','nip' => '19740302','jenis_kelamin' => 'Perempuan','agama' => 'Katholik','tempat_lahir' => 'Jakarta','tanggal_lahir' => '0000-00-00','alamat' => 'Pokoh Rt.001 Rw.019 Wedomartani Ngemplak','status' => 'GPNS','golongan' => 'III/C','mapel_tugas_pokok' => 'Teknik Komputer dan Jaringan','keterangan' => '','tugas_tambahan' => ''),
  array('id' => '6','nama' => 'Endang Sri Pujiastuti S.T.','nip' => '0','jenis_kelamin' => 'Perempuan','agama' => 'Islam','tempat_lahir' => 'Wonogiri','tanggal_lahir' => '0000-00-00','alamat' => 'NGLARANG RT/RW: 001/010, SIDOARUM. GODEAN, SLEMAN','status' => 'GTT','golongan' => '-','mapel_tugas_pokok' => 'Teknik Komputer dan Jaringan','keterangan' => '','tugas_tambahan' => ''),
  array('id' => '7','nama' => 'Emanuel Sigit Kuncoro S.ST.','nip' => '19601224','jenis_kelamin' => 'Laki-laki','agama' => 'Katholik','tempat_lahir' => 'Yogyakarta','tanggal_lahir' => '0000-00-00','alamat' => 'MRICAN, GANG BAMBANG TETUKO NO 3 YOGYAKARTA','status' => 'GPNS','golongan' => 'III/d','mapel_tugas_pokok' => 'Teknik Komputer dan Jaringan','keterangan' => '','tugas_tambahan' => ''),
  array('id' => '8','nama' => 'Ratna Yunita Sari S.T','nip' => '0','jenis_kelamin' => 'Perempuan','agama' => 'Islam','tempat_lahir' => 'Yogyakarta','tanggal_lahir' => '0000-00-00','alamat' => 'GENDENG GK 4/376 RT 54 RW 14 BACIRO GONDOKUSUMAN YOGYAKARTA','status' => 'GTT','golongan' => '-','mapel_tugas_pokok' => 'Teknik Komputer dan Jaringan','keterangan' => '','tugas_tambahan' => ''),
  array('id' => '9','nama' => 'Yunianto Hermawan S.Kom','nip' => '19730620','jenis_kelamin' => 'Laki-laki','agama' => 'Kristen','tempat_lahir' => 'Trucuk, Klaten','tanggal_lahir' => '0000-00-00','alamat' => 'DK. KLEMUDAN RT.026 RW.009 GADEN TRUCUK KLATEN','status' => 'GPNS','golongan' => 'III/C','mapel_tugas_pokok' => 'Teknik Komputer dan Jaringan','keterangan' => '','tugas_tambahan' => ''),
  array('id' => '10','nama' => 'Rumini S.Pd.','nip' => '19741217','jenis_kelamin' => 'Perempuan','agama' => 'Islam','tempat_lahir' => 'Sleman','tanggal_lahir' => '0000-00-00','alamat' => 'SAREN TEMPEL CT XV RT/RW 01/01 CATUR TUNGGAL DEPOK SLEMAN','status' => 'GCPNS','golongan' => 'III/a','mapel_tugas_pokok' => 'Penjaskes','keterangan' => '','tugas_tambahan' => ''),
  array('id' => '11','nama' => 'Ananto Tri Hartono','nip' => '0','jenis_kelamin' => 'Laki-laki','agama' => 'Islam','tempat_lahir' => 'Yogyakarta','tanggal_lahir' => '0000-00-00','alamat' => 'JL. GEJAYAN SANTREN GG MENUR','status' => 'PTT','golongan' => '-','mapel_tugas_pokok' => 'Juru Bengkel','keterangan' => '','tugas_tambahan' => ''),
  array('id' => '12','nama' => 'Nur Haryanti S.Pd.','nip' => '0','jenis_kelamin' => 'Perempuan','agama' => 'Islam','tempat_lahir' => 'Bantul','tanggal_lahir' => '0000-00-00','alamat' => 'REJODANI SARIHARJO NGAGLIK SLEMAN','status' => 'GTT','golongan' => '-','mapel_tugas_pokok' => 'Sejarah','keterangan' => '','tugas_tambahan' => ''),
  array('id' => '13','nama' => 'Rum Ismawati S.Si','nip' => '19780810','jenis_kelamin' => 'Perempuan','agama' => 'Islam','tempat_lahir' => 'Wonogiri','tanggal_lahir' => '0000-00-00','alamat' => 'SENDARI RT 01 RW 18 TIRTOADI MLATI SLEMAN','status' => 'GPNS','golongan' => 'III/d','mapel_tugas_pokok' => 'Matematika','keterangan' => '','tugas_tambahan' => ''),
  array('id' => '14','nama' => 'Heri Afrahatu Rahmah S.Pd.','nip' => '19681013','jenis_kelamin' => 'Perempuan','agama' => 'Islam','tempat_lahir' => 'Sleman','tanggal_lahir' => '0000-00-00','alamat' => 'DHURI RT 008 RW 002 TIRTOMARTANI KALASAN SLEMAN','status' => 'GPNS','golongan' => 'III/C','mapel_tugas_pokok' => 'Bahasa Inggris','keterangan' => '','tugas_tambahan' => ''),
  array('id' => '15','nama' => 'Drs. Zaris Danis Nofiar M.S.I.','nip' => '0','jenis_kelamin' => 'Laki-laki','agama' => 'Islam','tempat_lahir' => 'Sleman','tanggal_lahir' => '0000-00-00','alamat' => 'TEGALREJO, SUMBERSARI, MOYUDAN, SLEMAN','status' => 'PNS DEPAG','golongan' => 'IV/a','mapel_tugas_pokok' => 'Pendidikan Agama Islam','keterangan' => '','tugas_tambahan' => ''),
  array('id' => '16','nama' => 'Dra. Yuliana Sri Hartati','nip' => '19670723','jenis_kelamin' => 'Perempuan','agama' => 'Islam','tempat_lahir' => 'Sleman','tanggal_lahir' => '0000-00-00','alamat' => 'SAWAHAN RT 5/RW 19 PANDOWOHARJO,KECAMATAN SLEMAN','status' => 'GPNS','golongan' => 'IV/a','mapel_tugas_pokok' => 'Matematika','keterangan' => '','tugas_tambahan' => '')
);
